### PR TITLE
Improve language/locale processing

### PR DESCRIPTION
**Pull request by IanSav**
- Add new module "International.py" to handle all matters to do with Locale, Language or Countries.
- Add a new "LocaleSelection.py" screen to offer a better UI for Locale/Language selection.  This new screen also directly allows users to add or remove selected locales/languages.
- Update "StartEnigma.py" to support the new "International.py" and the removal of "Components/SetupDevices.py".
- Update "setup.xml" with new section to support "LocaleSelection.py".
- Update "menu.xml" to call the new "LocaleSelection" screen.
- Update "keymap.xml" to support the new "LocaleSelection" screen.
- Add a new "Language.py" module to provide hooks for legacy code and plugins to remap the old method calls into the new "International.py" module methods.
- Initialize the new "International.py" very early in "StartEnigma.py" so that all other modules can initialize with correct locale/language selections.
- Remove the locale/language initialization from "Components/SetupDevices.py".
- The existing "LanguageSelection" screen is deprecated but still functional and supported if required.
- Build "Tools/CountryCodes.py" "ISO3166" list from data defined in International.py.  This makes managing the country list easier as it needs only be done in one place within "International.py".  Eventually this module should be removed when all calls can be mapped directly to "International.py" methods.
- Update the WizardLanguage.py code to use the new LocaleSelection screen to replace the LanguageSelection screen.
- Update Hotkey.py code to use the new LocaleSelection screen to replace the LanguageSelection screen.

NOTE: The reason for creating a new "International.py" module is to clarify the use and meaning of "Locale", "Language" and "Country".  These terms should be interpreted as follows:
- Country: An official country as recognized by ISO, eg "AU" for Australia.
- Language: An official language as recognized by ISO, eg "en" for English.
- Locale: An official language as spoken in a country, eg "en_AU" for English (Australian).

### CODE REVIEW

**Review by norhap — CHANGES_REQUESTED** [review]
@IanSav 
the commit is incomplete, you should check Makefiles.
Add to Components International.py and remove SetupDevices.py.
You should also add to Makefile Screens LocaleSelection.py.

**Comment by IanSav** [comment]
- Makefile.am changes requested have been done.
- Merge conflict addressed.

Why are all the Python files specifically listed in the Makefile?  Other images use the "*.py" syntax.

**Comment by persianpros** [comment]
*.py makes errors in some build environments and we like PLi avoid it.

**Comment by IanSav** [comment]
That is odd, perhaps we should look at fixing that to make things easier in the future.  I hope it isn't an issue because of spaces or other strange characters in the file names.  This is often an issue if file arguments are not correctly protected.

**Comment by persianpros** [comment]
We can't.

This is related to make and ubuntu.

**Pull request merged**
