### PR TITLE
Refactor software update system

### PR DESCRIPTION
**Pull request by IanSav**
[SoftwareUpdate.py] Refactor code
- This change makes the software update function an internal function and screen.  The update feature no longer depends on external plugins.
- Rework and optimize the imports.
- This new code integrates fully with the refactored Opkg.py support module.
- Create a new update list screen.  This screen lists all the updates available together with the current version installed and the new version that will be used if the update is accepted.
- The update list is now sorted alphabetically to make user review of the changes easier.
- Update the "Traffic Light" mechanism for indicating the state of the feed.  The updates can have 4 states:
  All OFF -> There is an error obtaining the feed status.
  RED -> The feed is deemed to be problematic and updates are disabled.
  YELLOW -> There may be an issue or a pending update such that the use may choose not to update but can do so if they want.
  GREEN -> The feeds are operating normally.
- The new "Traffic Light" system is granular such that the status can be set individually for any supported model.  This system is supported by server side changes and enhancements.
- The new "Traffic Light" system also allows the system administrators to push informative messages to users regarding the state of the feed.
- The new code has embedded skins that skin developers can review to assist them in updating their skins to support the new code.
- The new code has HELP added to assist users in determining what buttons are available and their function.
- The GREEN / OK buttons will not be available if there are no updates or updates are disabled.
- The YELLOW button has been added to allow users to scan the server again to look for any update feed changes.
- The number of updates permitted before a flash is recommended can now be set in SystemInfo.py.  The default has been set to 200 updates.
- If the number of updates exceeds the flash threshold the user can still choose to attempt the upgrade if they so choose.
- If the user chooses to proceed with an update a new update progress screen is shown.  The new screen is a scrolling text window that lists all the key actions being performed.
- When the update completes the user is presented with a short summary list of counters of the key actions.
- The refactored Opkg.py includes enough logging information that should assist developers to identify and update related issues.  What is seen in this screen is just a summary of the actions carried out.
- Both screens have an activity scrollbar that gives the user a visible indication that the code is still running.  It is *NOT* an indicator of the relative progress through the tasks.
- Both screens now support front panel displays.

[Opkg.py] Refactor code
- Sort and optimize imports and improve some variable names.
- Make print statements Python 3 friendly.
- Replace file I/O with fileReadLines() and fileWriteLine() methods.
- Expand the CMD and EVENT types.
- Add methods to convert CMD and EVENT codes into text strings for logging.
- Add package exclude list processing.
- Specify "opkg" as a fully qualified path to avoid command hijacking.
- Use the ARGV style (list of arguments) for command processing.
- Directly execute /usr/bin/opkg rather than kicking off a shell.
- Remove the "-test" command line option, which is invalid, with the "--noaction" command line option to facilitate non destructive testing of the code.
- Any "busybox" updates are excluded from the upgrade stream and a flag is set to trigger the BusyBox upgrade just prior to a restart.  This task is handled by the "enigma2.sh" shell script.
- Optimize the opkg command output text processing.  Use a single buffer with a buffer pointer to extract each line from the command output.  This eliminates all the string copying and concatination.
- Optimize the parsing of the "opkg" output by doing a white space split of the lines rather than a single space character.
- Keep the original command output for debug logging.
- Enable the extraction and use of more "opkg" events with extended callbacks to the calling code.
- Only allow one entry for each callback into the callbackList.  Don't crash if a callback has already been removed.
- Don't send multiple newlines to "opkg" via the write() method.
- Add a large comment for the parseLine() method to demonstrate the syntax of "opkg" output that is processed.
- Improve, simplify and optimise the OpenATV provided exclude code.
- Simplify the command execution logic.
- Add a mechanism to sequence the the opkg runs so that the information is not overlapped and lost.
- Make the debug logging of the opkg output configurable via the debug config settings screen.
- Retask the update flag file to provide the *exact* upgrade function required to update *all* the BusyBox components.  Also ensure that *any* BusyBox components are correctly flagged for update.

[skin_default] Add images used by new SoftwareUpdate screen

[enigma2.sh.in] Add BusyBox update hook 
- This change adds the BusyBox update hook from the new software update system to do the actual BusyBox update.  This should be done inisolation and at a point with minimal risk to any running shell scripts.  This is best done just before a restart or halt.
- Use the BusyBox update function at all restart points.
- Move the BusyBox update function to after some initialisation tasks are completed.
- Retask the update flag file to provide the *exact* upgrade function required to update *all* the BusyBox components.

[StartEnigma.py] Add Opkg debugging option

[setup.xml] Add Opkg debugging option

Development of this code was greatly assisted by the efforts of @jbleyel and @WXbet.  @WXbet ran extensive tests on the code and made many other suggestions to improve the reliability and functionality of the code.  Also thanks to him for setting up a test feed to put the new Opkg and SoftwareUpdate thought some important but rare tests.

### CODE REVIEW

**Comment by WXbet** [comment]
This PR is not ready to merge!

@IanSav 
We need to update the following files:
image

And additionally it is nessessary to add the new icons to `data/skin_default/Makefile.am`.

**Comment by persianpros** [comment]
Is this finished?

**Comment by IanSav** [comment]
Not yet, the code is still being tested.  WXbet has a few more suggestions and corrections to contribute.

**Review by WXbet — APPROVED** [review]
All these changes were tested successfully.

**Comment by persianpros** [comment]
Is it ok to merge now?

**Pull request merged**
