### PR TITLE
Replace octagon6 with sf80082

### PR DESCRIPTION
**Pull request by IanSav**
Add sf80082 as next generation version of sf8008
- This remote control layout appears to be a new design for newer versions of the sf8008 receiver.
- This designation replaces the octagon6 version that was recently added.

[octagon6.png] Replaced by sf80082.png

[octagon6.xml] Replaced by sf80082.xml

[KeyBindings.py] Add new bindings …
- The "KEY_F4" and "KEY_KEYBOARD" definitions are used by the new sf80082 remote control.
- The "KEY_GOTO" definition appears to have been lost along the way.

### CODE REVIEW

**Comment by persianpros** [comment]
I think sf8008v2 is better than sf80082 but your call :+1:

**Comment by IanSav** [comment]
The "v" coding is not used for any other remote controls.  ;)

**Comment by persianpros** [comment]
I know but we have models like dm800se and dm800sev2 and this v2 is common in e2, no sf80082 is a new number.

**Comment by 4l3x2k** [comment]
Sorry @persianpros , but please do not forget to align the bb recipes again :-(.

Do we need the changes for OpenWebIf too?

**Comment by persianpros** [comment]
Yes all ;)

**Comment by IanSav** [comment]
Do you want to rename all these submissions to sf8008gold?

**Comment by persianpros** [comment]
sf8008gold or sf8008v2 would be better.

**Comment by 4l3x2k** [comment]
Never mind that a name can be that complicated!
I do not own the sf8008 in gold!
This is my last statement about naming a remote. My position is <manufacturer><number>. Maybe having a readme where assignments are listet. At OA-A it is listet in the Makefile.am.

**Comment by IanSav** [comment]
I agree with sf8008gold as the remote control identifier rather than sf8008v2.  ;)

**Comment by persianpros** [comment]
It could be even sf8008n which means new but for now I think this renaming is enough till later.

**Pull request merged**
