### PR TITLE
[International.py] Code enhancements

### PR DESCRIPTION
**Pull request by IanSav**
- Make the getAvailablePackages(), getInstalledPackages() and getPackageDirectories() methods support an update option so that the code can be used as a fetch method to return the values to other modules.  This was done to discourage developers from reaching into this module to look at the internal variables.
- Change the fall back value for setlocale() from "en_US" to "POSIX".  This frees up the image from needing to have the "en_US" full locale settings installed.
- Add the getLanguageTranslated() method to allow the translated name of the language to be accessed as a variable.
- Add a new method, getPurgablePackages(), that can be used to list all installed language/locale packages that are installed but not in the defined list, PERMANENT_LOCALES, of locales that should not be removed in a purge operation.  (Correct the getPurgablePackages() method to use a shallow copy of PERMANENT_LOCALES!)
- Add a new method, getPermanentLocales(), to report the locales nominated as permanent.
- Rework runPackageManager() to return a status value as well as a message to address potential language/translation issues.
- Add support for ISO 3166-2 subdivisions.  This change allows support for ISO 3166-2 country subdivision codes.  The subdivisions carry over the data from the parent ISO 3166 definitions.  The first such code to be added is "ES-GA" for the Galacia subdivision within Spain.  Thus Galacian will now have the locale code of "gl_ES-GA".

  Developers and skinners need to be aware that country codes may now be longer (typically 5 or more characters) for such subdivisions.  This change also means that all such subdivisions will now require their own flags names in the same style of the subdivision.  In this case the new flag will have the file name "es-ga.png".
- Use the phrase "locale/language" more consistently.

UPDATE:
- Rename getPackageDirectories() to getInstalledDirectories() as this method and associated variable was miss-named.  The method implied that packages were being listed when in fact it was installed locale and language directories.  This error led to the getPurgablePackages() method not working as intended.  This is now fixed.  Thanks to @jbleyel for helping diagnose the issue.

- Added the localeToPackage() and languageToPackage() methods to make similar data more readily available to other Enigma2 modules.

### CODE REVIEW

**Comment by persianpros** [comment]
Please remove de_DE and fr_FR, only English should be the min for OV :+1:

**Comment by IanSav** [comment]
The selected languages were selected as they are the most commonly used and understood around the world.  This limit gives most users a reasonable chance of being able to understand the UI.

Even these locales can be removed by the user manually.  That is, they won't be removed by a Purge but they can be individually selected and removed.

(The Purge option is a new option in the next version of LocaleSelection that will be finished soon.)

**Comment by IanSav** [comment]
By the way, this change will not cause the "permanent" locales to be installed if they are not installed!

**Review by norhap — CHANGES_REQUESTED** [review]
1.- Galicia is a Region of Spain where they have their own language-dialect and it is implemented in languages, therefore we must change ("ES",)) to ("GL",)) to be able to see the flag this region that we also have already added in the skin. 

By default we now see for this language galician the flag of Spain ("ES"), which is how it is written in the encoding. 

https://github.com/OpenVisionE2/enigma2-openvision/blob/982e2b24d1e6f82c3278af6bd527fc1e43ffcc52/lib/python/Components/International.py#L118

2.- Message warning that is present in a multitude of sites, for example in feed installations, in encoding of active processes such as softcam vision, etc ...

This message must be further filtered, so that it is present only when it really is an existing problem in the user's environment in its configuration.

https://github.com/OpenVisionE2/enigma2-openvision/blob/982e2b24d1e6f82c3278af6bd527fc1e43ffcc52/lib/python/Components/International.py#L606

**Comment by IanSav** [comment]
1)  If Galician is a language spoken in Spain then why isn't the Spanish flag appropriate?  The language will be displayed as "Galician" and not "Spanish".  The flags are not the only identifier.

Do they have their own flag?

2) I don't understand what you are saying / requesting.  This area of the code has not changed from before!

**Comment by norhap** [comment]
1.- Catalonia is also a region of Spain, and Catalan is spoken, and it has its own identifying flag, as in Galicia Galician and not Spanish is spoken, if a language is being implemented in its dialect as is the case of Catalonia, we must also leave it to Galicia, which is also Spanish ... since Galicia also has its own flag as do each of the regions that make up the country of Spain, the difference is that many of these regions speak Spanish, except for some in which Find Basque Basque, Galicia, Catalonia, Valencian. 

2.- It has not changed, but the problem is there, in the Skype chat I let him know with images and it has not been corrected in these PR, there is a warning message that I made him see in the chat on one of many screens in which it is located, that code that I show you must restrict it much more because the message is everywhere is very annoying ... if you do not remember it, look at my Skype chat messages and look at one of the photos that I put on it.

**Comment by IanSav** [comment]
1) Please provide me with all the ISO details for the Galicia identify so I can add it to the country data.  Then it can have its own flag as part of the official data.  I searched for the data and I couldn't find any information (https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).  By the way, "GA" is for Gabon.

This is all I could find for Galicia - https://en.wikipedia.org/wiki/Galicia_(Spain).

2) I am working on very many things at the same time.  You will have to be far more specific.  Please don't send me on hunts to find and work out what you mean.  Be specific and provide appropriate information and details.

I didn't see the point on setting the shell environment variables as the locale files are not usually installed.  However this is what was done before so I kept the code in case there was some obscure purpose.  I am also told that BusyBox doesn't use the locale settings (I don't know if this is true).

The further risk of setting the shell language for Enigma2 sub shells is that much of Enigma2 evaluates the return of sub shells as English.  If the language does change then this can create problems.  That is why I now return the exit code for the "opkg" command to eliminate language based parsing errors.

**Comment by norhap** [comment]
I have seen this message in busybox by telnet, I see it in opkg + command, I see it in any call of active processes such as open processes on the vison softcam screen, the message and the image is in the chat, it is not I send him to hunt, I am warning him that the warning message is visible everywhere, and I am indicating the code and the line that causes it, in fact I have this line commented in my enigma2 to avoid these messages, but obviously it will not be the best solution but it is the one that makes me get rid of such annoying messages.

From there it is your code, so I can not give you more data I think I am being explicit and I expose the line that causes this message. From here, accept the problem as you see fit.

The Galician issue is not in the ISO effectively, but it is a dialect that is fully implemented recently by a user in the PLi environment and also merged in OV, therefore the behavior must be exactly the same as we do in Catalonia, where We see its flag and if the user from Catalonia wishes to have their language, then choose it, as Galicia can.

For example, in my enigma2 I simply change ES to GL to have both the dialect available for Galicia and its flag identification, but I suppose it is not ideal, or maybe if I do not know, this is where you should undertake what it should be .

**Comment by IanSav** [comment]
When working through language issues with OpenATV I was provided with log messages and screen captures demonstrating the issue together with English translations to help me understand the information I was given (in German).  The error I fixed does not occur in English so it never happened in any of my testing.  I suspect that something similar is happening to you.  I wouldn't be asking for more information if I could see what you are seeing.  You have mentioned messages from BusyBox and opkg but have not posted any specific examples.  Examples are part of the more information I am requesting.  The other part is instructions on how to trigger or demonstrate the issue.

Have you tested the code?  Galician is definitely a selectable language already!  I had that code written and running well before OpenPLi.

(UPDATE: I have found some extra information about Galicia where I may be able to enhance the UI.  I will experiment more with this new found data.)

**Comment by IanSav** [comment]
ISO 3166-2 country subdivision capabilities have been added.  This now allows Galicia to be added as a separate entity with its own flag.

Please note the changes and warning in the commit notes.

**Review by norhap — APPROVED** [review]

**Pull request merged**
