### PR TITLE
Add Octagon RCU introduced with SF8008 Gold Edition

### PR DESCRIPTION
**Pull request by 4l3x2k**
Needs to be enabled in
meta-octagon/conf/machine/include/octagon-hisi.inc
with RCNAME="octagon5"

### CODE REVIEW

**Comment by persianpros** [comment]
If you want to avoid sf names then this should be octagon6 as there are 5 sf remotes for e2 ;)

**Comment by 4l3x2k** [comment]
> is there a way to detect this? is something different like proc file or something?

I did not checked it but I think there is not. The SF8008 Combo from @norhap has this RCU included.

**Comment by persianpros** [comment]
Hmm then how you use it?

I can update bb recipes to include both but how to detect and use it?

**Comment by 4l3x2k** [comment]
I simply using it.

I think there will be no solution to detect a rcu. We need to tell enigma to use these .png and .xml and the user tells enigma.

**Comment by persianpros** [comment]
Then we need to add the ability to change it.

**Comment by 4l3x2k** [comment]
There may some development afford, right. Point me in some direction. Maybe open a issue and assign or let discuss in the forum. Maybe @IanSav has some hints on this.

With this PR the "lower" bits are set up. Picture and key definition. How to choose is another question.

**Comment by IanSav** [comment]
Sorry for the delay in responding, I only just noticed the email notification of this thread.

I will "jazz" up this new remote control to add all the new bits.  As for selecting which remote control to use that is part of my new proposed remote control management updates to InputDevice.py and InputDeviceSetup.py.  These are not yet ready for review and use but are near the top of the to-do list.

**Comment by persianpros** [comment]
@4l3x2k @petrkr 

I had to disable some lines of https://github.com/OpenVisionE2/enigma2-openvision/commit/7ef51be167d68ca8ff5a7a228e17a83b005eb45d for new EPG API changes so if you had time please take a look at it and restore it if you can.

**Comment by petrkr** [comment]
> Then we need to add the ability to change it.

Yes.
In Setup -- UI -- Input should be two (or more) receivers to select. Because I have that original one. New drivers does not mean you need new RC. And also I do not know why many peoples with original RC must be forced to have new RC in GUI that is not much common yet.
Also that new one works with my old RC too (I thin @norhap tested that).

I will go with selection in that UI and in initial wizard, if image detects there are more than one RC, it will add screen to select right one during initial setup.

As workaround could be done now "extension" same as skin which can replace XML from plugins menu.

**Comment by petrkr** [comment]
> Then we need to add the ability to change it.

Yes.
In Setup -- UI -- Input should be two (or more) receivers to select. Because I have that original one. New drivers does not mean you need new RC. And also I do not know why many peoples with original RC must be forced to have new RC in GUI that is not much common yet.
Also that new one works with my old RC too (I thin @norhap tested that).

I will go with selection in that UI and in initial wizard, if image detects there are more than one RC, it will add screen to select right one during initial setup.

As workaround could be done now "extension" same as skin which can replace XML from plugins menu.

**Comment by IanSav** [comment]
@4l3x2k, can you please confirm the Enigma2 code that is transmitted by the CONTEXT button.  You have the value defined as 374 but that is KEY_KEYBOARD and not KEY_CONTEXT_MENU which is value 438.

Also this definition will require changes to KeyBindings.py to become valid as there is no current definition for F4.

**Comment by 4l3x2k** [comment]
> @4l3x2k, can you please confirm the Enigma2 code that is transmitted by the CONTEXT button. You have the value defined as 374 but that is KEY_KEYBOARD and not KEY_CONTEXT_MENU which is value 438.

The key code 374 is reported by /dev/input/event0. I used the script from https://stackoverflow.com/a/16682549 to get all key events and key codes while in init 4.
I'll check that again with latest drivers.

> Also this remote control definition will require changes to KeyBindings.py to become valid as there is no current definition for KEY_F4 (nor KEY_KEYBOARD if that is the correct code for the CONTEXT button).

Yes.
I just released the "lower" bits yet because there seem to be some other long term plans I have no idea regarding keybindings and input.
I could create a new rcu id for this remote in keybindings.py. Would it help you to reach long term plans?

**Comment by 4l3x2k** [comment]
@persianpros 
> @4l3x2k @petrkr
> 
> I had to disable some lines of [7ef51be](https://github.com/OpenVisionE2/enigma2-openvision/commit/7ef51be167d68ca8ff5a7a228e17a83b005eb45d) for new EPG API changes so if you had time please take a look at it and restore it if you can.

Hot discussion for this refactoring by betacentauri.

So, a or the test case here would be:
```
1. delete / clear EPG cache (<!-- Menu / Setup / EPG -->)
2. Zap to a service / channel
2.1 EIT EPG is filled within 1/2 second (Australia) or within 2 seconds (Others)
2.2 EIT EPG is filled within 5 minutes (Australia) or within 60 minutes (Others)
```
right?
Maybe this change isn't required anymore?

This is quite out of my scope but quick and dirty fix would be making epgcache a friend of epgtransponderdatareader.

I need to dig to get an idea of the whole thing. That is hard to read all this cpp stuff.

**Comment by IanSav** [comment]
@4l3x2k, thanks for the remote control update.  The button code being used is very unexpected but it is what it is.  Don't worry I will complete the fixes to the remote control template and I will update OpenVision, OpenPLi and OpenATV with the enhancements to KeyBindings.py.  (Yes KeyBindings.py is going to go away but I am not there yet.  ;) )

**Comment by IanSav** [comment]
I am not sure why this topic is in this thread but...
> ```
> 1. delete / clear EPG cache ()
> 2. Zap to a service / channel
> 2.1 EIT EPG is filled within 1/2 second (Australia) or within 2 seconds (Others)
> 2.2 EIT EPG is filled within 5 minutes (Australia) or within 60 minutes (Others)
> ```

Australia only has 7 days of advance EPG data and it can be fully loaded within about 2 minutes.  I think it can be done within a minute but I usually allow 2 just to be sure.  The Now/Next data is significantly more frequent.

If anyone wants raw data captures of Australian TV (as broadcast in Melbourne) please ask me.  I am pretty sure that I can capture all the streams without the audio or video streams.

**Comment by IanSav** [comment]
@4l3x2k If I post the latest version of this remote control on OpenVision will you be able to test it from there?

**Comment by 4l3x2k** [comment]
@IanSav
> @4l3x2k, thanks for the remote control update. The button code being used is very unexpected but it is what it is. Don't worry I will complete the fixes to the remote control template and I will update OpenVision, OpenPLi and OpenATV with the enhancements to KeyBindings.py. (Yes KeyBindings.py is going to go away but I am not there yet. ;) )

I checked it again with openvision-10.2-r370
```
root@sf8008:~# init 4
root@sf8008:~# python inputevent.py 
Event type 4, code 4, value 100289715 at 1616242522.101797
Event type 1, code 374, value 1 at 1616242522.101797
===========================================
Event type 1, code 374, value 0 at 1616242522.311006
===========================================
^CTraceback (most recent call last):
  File "inputevent.py", line 31, in <module>
    event = in_file.read(EVENT_SIZE)
KeyboardInterrupt
root@sf8008:~#
```

enigma2 gives 
```
<   742.7562> 13:20:09.6439 [eInputDeviceInit] 1 176 (374) 1
<   742.7563> 13:20:09.6440 [eRCDeviceInputDev] map: 374->227
<   742.7564> 13:20:09.6440 [eRCDeviceInputDev] emit: 1
<   742.7575> 13:20:09.6452 2021-03-20 13:20:09+0100 [-] [InfoBarGenerics] Key: 227 (Make) KeyID='KEY_SWITCHVIDEOMODE' Binding='VMODE'.
<   742.7889> 13:20:09.6766 2021-03-20 13:20:09+0100 [-] [VfdSymbols] Write to /proc/stb/fp/ledpowercolor
<   743.0736> 13:20:09.9613 [eInputDeviceInit] 0 176 (374) 1
<   743.0737> 13:20:09.9614 [eRCDeviceInputDev] map: 374->227
<   743.0737> 13:20:09.9614 [eRCDeviceInputDev] emit: 0
<   743.0750> 13:20:09.9627 2021-03-20 13:20:09+0100 [-] [InfoBarGenerics] Key: 227 (Break) KeyID='KEY_SWITCHVIDEOMODE' Binding='VMODE'.
<   743.0762> 13:20:09.9639 2021-03-20 13:20:09+0100 [-] [ActionMap] Keymap 'InfobarVmodeButtonActions' -> Action = 'vmodeSelection'.
<   743.0774> 13:20:09.9651 2021-03-20 13:20:09+0100 [-] [Videomode] VideoHardware -> setting aspect, policy, policy2, wss 16:9 bestfit panscan auto
<   743.0779> 13:20:09.9656 2021-03-20 13:20:09+0100 [-] [Videomode] Write to /proc/stb/video/aspect
<   743.0786> 13:20:09.9663 2021-03-20 13:20:09+0100 [-] [Videomode] Write to /proc/stb/video/policy
<   743.0803> 13:20:09.9680 2021-03-20 13:20:09+0100 [-] [Videomode] Write to /proc/stb/denc/0/wss
<   743.0813> 13:20:09.9690 2021-03-20 13:20:09+0100 [-] [Videomode] Write to /proc/stb/video/policy2
<   743.0827> 13:20:09.9704 2021-03-20 13:20:09+0100 [-] [Screen] Showing screen 'VideoMode'.
```

> @4l3x2k If I post the latest version of this remote control on OpenVision will you be able to test it from there?
> 
> Also is this remote control meant to be Octagon7 or is this an update for Octagon6? On the OE-Alliance you submitted this as Octagon7 yet here is is Octagn6. Please confirm which designation is correct. (Particularly when I can't see any other Octagon remote controls in either list!)

I'am using the Image provided by @petrkr, but if there are only .py, .png, .xml, .html changes I can replace files on the box.

Well, there is actually no octagonX remote control. They are called sf8008, sf4008 and so on. At the OE-A I count one more sf... remote control. That's why it is octagon7 at OE-A. I really don't know whether there are remotes for octagon sx receivers. Like this 



So we can call it what we want, it is just a name. But I'am used to the scheme used by vu, zgemma, gb and so on. So we can call it octagon1 for example.

**Comment by 4l3x2k** [comment]
@IanSav
@petrkr provides quite recent images for sf8008 so I could also test enigma2 binary changes.

**Comment by IanSav** [comment]
@4l3x2k I can't attache the files I need to give you here.  How else can I get them to you?

**Comment by 4l3x2k** [comment]
@IanSav 
If you do not want to push the changes to ov you could use public google drive, dropbox, mediafire or maybe GitHub gists?

It is not possible to zip the files with directory structure included by dragging them here? So I could simply unzip it on the box and got all in place. Like a simple ipk.

**Comment by IanSav** [comment]
Can you access Skype?  You could join the developers chat area.

Let me try to zip up the bits to post them here.

**Comment by IanSav** [comment]
I have never seen a remote control with a button labelled CONTEXT that doesn't send the KEY_CONTEXT_MENU code!

**Comment by IanSav** [comment]
If you would like to join us on Skype please let me know your account and I will invite you in.

**Comment by 4l3x2k** [comment]
Look like every button is crashing now.

[HELP-Button_enigma2_crash_2021-03-20_14-27-09.log](https://github.com/OpenVisionE2/enigma2-openvision/files/6175657/HELP-Button_enigma2_crash_2021-03-20_14-27-09.log)
[MENU-Button_enigma2_crash_2021-03-20_14-28-34.log](https://github.com/OpenVisionE2/enigma2-openvision/files/6175658/MENU-Button_enigma2_crash_2021-03-20_14-28-34.log)
[OK-Button_enigma2_crash_2021-03-20_14-30-31.log](https://github.com/OpenVisionE2/enigma2-openvision/files/6175659/OK-Button_enigma2_crash_2021-03-20_14-30-31.log)


Your KeyBinding.py diff is this from current
```
--- Desktop/enigma2-openvision/lib/python/Tools/KeyBindings.py	2021-03-12 17:54:10.000000000 +0100
+++ Downloads/Remote/KeyBindings.py	2021-03-20 03:22:30.000000000 +0100
@@ -1,5 +1,4 @@
 from keyids import KEYIDS
-from Components.config import config
 
 keyBindings = {}
 
@@ -160,15 +159,17 @@
 	KEYIDS["KEY_F1"]: ("F1",),
 	KEYIDS["KEY_F2"]: ("F2",),
 	KEYIDS["KEY_F3"]: ("F3",),
+	KEYIDS["KEY_F4"]: ("F4",),
 	KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
 	KEYIDS["KEY_FAVORITES"]: ("FAV",),
 	KEYIDS["KEY_FILE"]: ("LIST",),
 	KEYIDS["KEY_GREEN"]: ("GREEN",),
+	KEYIDS["KEY_GOTO"]: ("GOTO",),  # Missing.
 	KEYIDS["KEY_HELP"]: ("HELP",),
 	KEYIDS["KEY_HOME"]: ("HOME",),
 	KEYIDS["KEY_HOMEPAGE"]: ("HOMEPAGE",),
 	KEYIDS["KEY_INFO"]: ("INFO",),
-	KEYIDS["KEY_LAST"]: ("BACK",),
+	KEYIDS["KEY_KEYBOARD"]: ("KEYBOARD",),
 	KEYIDS["KEY_LEFT"]: ("LEFT",),
 	KEYIDS["KEY_LIST"]: ("PLAYLIST",),
 	KEYIDS["KEY_MEDIA"]: ("MEDIA",),
@@ -368,7 +369,7 @@
 
 def getKeyDescription(key):
 	# rcType = config.misc.inputdevices.rcType.value  # This is a proposed new config location.
-	rcType = config.plugins.remotecontroltype.rctype.value
+	# rcType = config.plugins.remotecontroltype.rctype.value
 	# print("[KeyBindings] RC type is '%s'." % rcType)
 	if rcType == 14:  # XP1000
 		idx = 3
@@ -376,7 +377,7 @@
 		idx = 4
 	else:
 		idx = 2
-	return keyDescriptions[idx].get(key, ("None",))
+	return keyDescriptions[idx].get(key)
 
 
 def getKeyBindingKeys(filterfn=lambda key: True):
```

**Comment by IanSav** [comment]
Do you have Skype, I would like to work with you more interactively.  If not are you on IRC?

The logs file you provided are not in debug mode so there is nothing for me to review.

**Comment by 4l3x2k** [comment]
> This zip file has the new remote control files and an updated KeyBindings.py to make them valid. I called the remote controls Octagon6 but perhaps they should be sf80082?

If there will never be a device like sf80082 it is ok, but who knows?

> Do you have Skype, I would like to work with you more interactively. If not are you on IRC?
> 
> The logs file you provided are not in debug mode so there is nothing for me to review.

IRC would be ok. Or slack.

**Comment by IanSav** [comment]
Can you contact me on Slack "IanSav".  If that doesn't work I am also in #OpenVision on IRC.

**Comment by 4l3x2k** [comment]
Crash logs with debug enabled

[HELP-Button_enigma2_crash_2021-03-20_15-02-54.log](https://github.com/OpenVisionE2/enigma2-openvision/files/6175734/HELP-Button_enigma2_crash_2021-03-20_15-02-54.log)
[MENU-Button_enigma2_crash_2021-03-20_15-03-44.log](https://github.com/OpenVisionE2/enigma2-openvision/files/6175735/MENU-Button_enigma2_crash_2021-03-20_15-03-44.log)
[OK-Button_enigma2_crash_2021-03-20_15-04-11.log](https://github.com/OpenVisionE2/enigma2-openvision/files/6175736/OK-Button_enigma2_crash_2021-03-20_15-04-11.log)

**Pull request merged**
