### PR TITLE
RC: VU+ Duo

### PR DESCRIPTION
**Pull request by petrkr**
Fixed definitions file for VU+ Duo remote control,
- replaced image to match real remote (Thanks IanSav for image)
- new XML format based on IanSav which fixed HELP button act as EPG
- corrected button positions

### CODE REVIEW

**Comment by 4l3x2k** [comment]
Are attributes
- keyid
- title="Mute"
- shape="circle"
- radius="9"

necessary to function with IanSav changes?

**Comment by petrkr** [comment]
For this iteration not, but next iteration will be remove html on openwebif and it will use this xml as data source. 

And keyid is also new rc model which support remapping on RC leven, old version uses hard-coded remaps in C++ code enabled by compile definitions.

So atlest keyid and remap are good to use already now.

**Comment by petrkr** [comment]
Final check is pass for me. Tested on r370.

image
image

**Comment by 4l3x2k** [comment]
I use shape="rect" in my sf8008.html.

How would this look in the sf8008.xml? How to name the attribute that defines the rect?

```
		<button keyid="KEY_NEXT" name="ARROWRIGHT" title="Next" pos="95,158" shape="circle" radius="9" />
		<button keyid="KEY_F1" name="F1" title="Function 1" pos="22,179" shape="rect" xy="31,184" />
```

**Comment by petrkr** [comment]
I will commit sf4008 soon, so you can inspirate there, I think it has almost same remote as sf4008

**Comment by petrkr** [comment]
and I will need sf8008 too as I have it in hometown.

**Comment by 4l3x2k** [comment]
I want to upgrade to this one 

https://www.octagon-germany.eu/wp-content/uploads/2020/11/Octagon_SF8008-Gold-Combo_fb-rcu2.jpg

I do not own the gold edition, but got that remote control!

**Comment by petrkr** [comment]
Aha, so it must be done as new remote, since sf8008 is already that old version. Have to ask @IanSav how to do 2nd remote for same receiver

**Comment by persianpros** [comment]
https://github.com/OpenVisionE2/meta-octagon/commit/4683aa0b5a1445322c1548af303a827bc80f99a3

**Comment by 4l3x2k** [comment]
After last commits made I see that shape rect need the size attribute.

@IanSav 
Do not forget that the html rendering (map > area > shape="rect") need absolute positions!
So
```
shape="rect" coords="0,0,10,10"
```
does not say that the rect is 10 in height and width!
It is more like "span over"!

**Comment by petrkr** [comment]
I push there sf8008.xml for v1 remote, you have to do some sf8008v2.xml proably or if that remote has some official name.  I was about create one, but if you already works on it I will keep it for you :)

Also do not forgot add also buttons which E2 does not use. Also best do first HTML and use Firefox plugin to check results (https://addons.mozilla.org/en-US/firefox/addon/ime/)

**Comment by petrkr** [comment]
Also keep maximum height of picture 500px and maximum width around 150px (what comes first)

**Comment by 4l3x2k** [comment]
Ok I see.
But please no sf8008v2 or something like that!

Many manufacturers went through this hell and we should name the RC rather than the STB!

I do not want to see anything like "vuduo" or "vuduo". Be more specific "sf8008v1" and "sf8008v2".

The RC is a device like any other STB! So get in touch with that!

**Comment by petrkr** [comment]
Agree with you, that is why i wrote "or if that remote has some official name"

**Comment by petrkr** [comment]
Already also VU Duo has same remote as Solo, and Zero... but not as Duo 2 or Solo 2, that is different (littlebit, but it is).. And friend post me for his VU Solo2 two different (totaly - same as sf8008 did) remotes

**Comment by petrkr** [comment]
maybe can go with picture like this one ?

sf8008 new remote

**Comment by 4l3x2k** [comment]
> maybe can go with picture like this one ?
> 
> sf8008 new remote

Look like mine .png.

Here is the .xml
```
<rcs>
	<rc id="2">
		<button keyid="KEY_POWER" name="POWER" title="Power" pos="95,27" shape="circle" radius="9" />
		<button keyid="KEY_1" name="1" title="1" pos="25,74" shape="circle" radius="9" />
		<button keyid="KEY_2" name="2" title="2 (ABC)" pos="60,74" shape="circle" radius="9" />
		<button keyid="KEY_3" name="3" title="3 (DEF)" pos="95,74" shape="circle" radius="9" />
		<button keyid="KEY_4" name="4" title="4 (GHI)" pos="25,102" shape="circle" radius="9" />
		<button keyid="KEY_5" name="5" title="5 (JKL)" pos="60,102" shape="circle" radius="9" />
		<button keyid="KEY_6" name="6" title="6 (MNO)" pos="95,102" shape="circle" radius="9" />
		<button keyid="KEY_7" name="7" title="7 (PQRS)" pos="25,130" shape="circle" radius="9" />
		<button keyid="KEY_8" name="8" title="8 (TUV)" pos="60,130" shape="circle" radius="9" />
		<button keyid="KEY_9" name="9" title="9 (WXYZ)" pos="95,130" shape="circle" radius="9" />
		<button keyid="KEY_PREVIOUS" name="ARROWLEFT" title="Previous" pos="25,158" shape="circle" radius="9" />
		<button keyid="KEY_0" name="0" title="0" pos="60,158" shape="circle" radius="9" />
		<button keyid="KEY_NEXT" name="ARROWRIGHT" title="Next" pos="95,158" shape="circle" radius="9" />
		<button keyid="KEY_F1" name="F1" title="Function 1" pos="22,179" shape="rect" xy="31,184" />
		<button keyid="KEY_F2" name="F2" title="Function 2" pos="47,179" shape="rect" xy="56,184" />
		<button keyid="KEY_MUTE" name="MUTE" title="Mute" pos="22,198" shape="rect" xy="31,203" />
		<button keyid="KEY_HELP" name="HELP" title="Help" pos="73,198" shape="rect" xy="82,203" />
		<button keyid="KEY_F3" name="MAGIC" title="Function 3" pos="98,198" shape="rect" xy="107,203" />
		<button keyid="KEY_MENU" name="MENU" title="Menu" pos="20,222" shape="circle" radius="9"/>
		<button keyid="KEY_UP" name="UP" title="Up" pos="59,226" shape="rect" xy="68,231" />
		<button keyid="KEY_EXIT" name="EXIT" title="Exit" pos="100,222" shape="circle" radius="9" />
		<button keyid="KEY_LEFT" name="LEFT" title="Left" pos="32,253" shape="rect" xy="41,258" />
		<button keyid="KEY_OK" name="OK" title="OK" pos="60,253" shape="circle" radius="9" />
		<button keyid="KEY_RIGHT" name="RIGHT" title="Right" pos="88,253" shape="rect" xy="97,258" />
		<button keyid="KEY_INFO" name="INFO" title="Info" pos="21,287" shape="circle" radius="9" />
		<button keyid="KEY_DOWN" name="DOWN" title="Down" pos="59,280" shape="rect" xy="68,285" />
		<button keyid="KEY_BACK" name="RECALL" title="Back" pos="98,286" shape="circle" radius="9" />
		<button keyid="KEY_VOLUMEUP" name="VOL+" title="Vol +" pos="27,314" shape="rect" xy="36,319" />
		<button keyid="KEY_VIDEO" name="VIDEO" title="Video" pos="60,316" shape="rect" xy="69,321" />
		<button keyid="KEY_CHANNELUP" name="BOUQUET+" title="Ch +" pos="92,314" shape="rect" xy="101,319" />
		<button keyid="KEY_VOLUMEDOWN" name="VOL-" title="Vol -" pos="27,347" shape="rect" xy="36,352" />
		<button keyid="KEY_EPG" name="EPG" title="EPG" pos="60,342" shape="rect" xy="69,347" />
		<button keyid="KEY_CHANNELDOWN" name="BOUQUET-" title="Ch -" pos="92,347" shape="rect" xy="101,352" />
		<button keyid="KEY_RED" name="RED" title="Red" pos="22,367" shape="rect" xy="31,372" />
		<button keyid="KEY_GREEN" name="GREEN" title="Green" pos="47,367" shape="rect" xy="56,372" />
		<button keyid="KEY_YELLOW" name="YELLOW" title="Yellow" pos="72,367" shape="rect" xy="81,372" />
		<button keyid="KEY_BLUE" name="BLUE" title="Blue" pos="97,367" shape="rect" xy="106,372" />
		<button keyid="KEY_REWIND" name="REWIND" title="Rewind" pos="22,386" shape="rect" xy="31,391" />
		<button keyid="KEY_PLAY" name="PLAY" title="Play" pos="47,386" shape="rect" xy="56,391" />
		<button keyid="KEY_PAUSE" name="PAUSE" title="Pause" pos="72,386" shape="rect" xy="81,391" />
		<button keyid="KEY_FASTFORWARD" name="FASTFORWARD" title="Fast Forward" pos="97,386" shape="rect" xy="106,391" />
		<button keyid="KEY_AUDIO" name="AUDIO" title="Audio" pos="22,405" shape="rect" xy="31,410" />
		<button keyid="KEY_STOP" name="STOP" title="Stop" pos="47,405" shape="rect" xy="56,410" />
		<button keyid="KEY_RECORD" name="RECORD" title="Record" pos="72,405" shape="rect" xy="81,410" />
		<button keyid="KEY_KEYBOARD" name="CONTEXT" remap="KEY_CONTEXT_MENU" title="Context" pos="97,405" shape="rect" xy="106,410" />
		<button keyid="KEY_TEXT" name="TEXT" title="Text" pos="22,424" shape="rect" xy="31,429" />
		<button keyid="KEY_SUBTITLE" name="SUBTITLE" title="Subtitle" pos="47,424" shape="rect" xy="56,429" />
		<button keyid="KEY_TV" name="TV" title="TV" pos="72,424" shape="rect" xy="81,429" />
		<button keyid="KEY_TV" name="RADIO" title="Radio" pos="72,424" shape="rect" xy="81,429" />
		<button keyid="KEY_FAVORITES" name="FAVORITES" title="Favourites" pos="97,424" shape="rect" xy="106,429" />
	</rc>
</rcs>
```

and here is the .html
```
<img border='0' src='/images/remotes/sf8008.png' usemap='#map' >
<map name="map">
	<area shape="circle" onclick="pressMenuRemote('116');" title="Power" coords="95,27,9" />
	<area shape="circle" onclick="pressMenuRemote('2');" title="1" coords="25,74,9" />
	<area shape="circle" onclick="pressMenuRemote('3');" title="2 (ABC)" coords="60,74,9" />
	<area shape="circle" onclick="pressMenuRemote('4');" title="3 (DEF)" coords="95,74,9" />
	<area shape="circle" onclick="pressMenuRemote('5');" title="4 (GHI)" coords="25,102,9" />
	<area shape="circle" onclick="pressMenuRemote('6');" title="5 (JKL)" coords="60,102,9" />
	<area shape="circle" onclick="pressMenuRemote('7');" title="6 (MNO)" coords="95,102,9" />
	<area shape="circle" onclick="pressMenuRemote('8');" title="7 (PQRS)" coords="25,130,9" />
	<area shape="circle" onclick="pressMenuRemote('9');" title="8 (TUV)" coords="60,130,9" />
	<area shape="circle" onclick="pressMenuRemote('10');" title="9 (WXYZ)" coords="95,130,9" />
	<area shape="circle" onclick="pressMenuRemote('412');" title="Previous" coords="25,158,9" />
	<area shape="circle" onclick="pressMenuRemote('11');" title="0" coords="60,158,9" />
	<area shape="circle" onclick="pressMenuRemote('407');" title="Next" coords="95,158,9" />
	<area shape="rect" onclick="pressMenuRemote('59');" title="Function 1" coords="13,174,31,184" />
	<area shape="rect" onclick="pressMenuRemote('60');" title="Function 2" coords="38,174,56,184" />
	<area shape="rect" onclick="pressMenuRemote('113');" title="Mute" coords="13,193,31,203" />
	<area shape="rect" onclick="pressMenuRemote('138');" title="Help" coords="64,193,82,203" />
	<area shape="rect" onclick="pressMenuRemote('61');" title="Function 3" coords="89,193,107,203" />
	<area shape="circle" onclick="pressMenuRemote('139');" title="Menu" coords="20,222,9" />
	<area shape="rect" onclick="pressMenuRemote('103');" title="Up" coords="50,221,68,231" />
	<area shape="circle" onclick="pressMenuRemote('174');" title="Exit" coords="100,222,9" />
	<area shape="rect" onclick="pressMenuRemote('105');" title="Left" coords="23,248,41,258" />
	<area shape="circle" onclick="pressMenuRemote('352');" title="OK" coords="60,253,9" />
	<area shape="rect" onclick="pressMenuRemote('106');" title="Right" coords="79,248,97,258" />
	<area shape="circle" onclick="pressMenuRemote('358');" title="Info" coords="21,287,9" />
	<area shape="rect" onclick="pressMenuRemote('108');" title="Down" coords="50,275,68,285" />
	<area shape="circle" onclick="pressMenuRemote('158');" title="Back" coords="98,286,9" />
	<area shape="rect" onclick="pressMenuRemote('115');" title="Vol +" coords="18,309,36,319" />
	<area shape="rect" onclick="pressMenuRemote('393');" title="Video" coords="51,311,69,321" />
	<area shape="rect" onclick="pressMenuRemote('402');" title="Ch +" coords="83,309,101,319" />
	<area shape="rect" onclick="pressMenuRemote('114');" title="Vol -" coords="18,342,36,352" />
	<area shape="rect" onclick="pressMenuRemote('365');" title="EPG" coords="51,337,69,347" />
	<area shape="rect" onclick="pressMenuRemote('403');" title="Ch -" coords="83,342,101,352" />
	<area shape="rect" onclick="pressMenuRemote('398');" title="Red" coords="13,362,31,372" />
	<area shape="rect" onclick="pressMenuRemote('399');" title="Green" coords="38,362,56,372" />
	<area shape="rect" onclick="pressMenuRemote('400');" title="Yellow" coords="63,362,81,372" />
	<area shape="rect" onclick="pressMenuRemote('401');" title="Blue" coords="88,362,106,372" />
	<area shape="rect" onclick="pressMenuRemote('168');" title="Rewind" coords="13,381,31,391" />
	<area shape="rect" onclick="pressMenuRemote('207');" title="Play" coords="38,381,56,391" />
	<area shape="rect" onclick="pressMenuRemote('119');" title="Pause" coords="63,381,81,391" />
	<area shape="rect" onclick="pressMenuRemote('208');" title="Fast Forward" coords="88,381,106,391" />
	<area shape="rect" onclick="pressMenuRemote('392');" title="Audio" coords="13,400,31,410" />
	<area shape="rect" onclick="pressMenuRemote('128');" title="Stop" coords="38,400,56,410" />
	<area shape="rect" onclick="pressMenuRemote('167');" title="Record" coords="63,400,81,410" />
	<area shape="rect" onclick="pressMenuRemote('374');" title="Context" coords="88,400,106,410" />
	<area shape="rect" onclick="pressMenuRemote('388');" title="Text" coords="13,419,31,429" />
	<area shape="rect" onclick="pressMenuRemote('370');" title="Subtitle" coords="38,419,56,429" />
	<area shape="rect" onclick="pressMenuRemote('377');" title="TV" coords="63,419,81,429" />
	<area shape="rect" onclick="pressMenuRemote('377');" title="Radio" coords="63,419,81,429" />
	<area shape="rect" onclick="pressMenuRemote('364');" title="Favourites" coords="88,419,106,429" />
</map>
```

But we have driver changes that enable F3 and F4 so please wait.

**Comment by 4l3x2k** [comment]
Uploading ...
Yes. We can go with that .png!

**Comment by petrkr** [comment]
Yes drivers are already up, I building now.. I already have base image, now doing feed. But drivers are already done... But better to wait for whole image than pick-up package by package...
give me like 1hour

**Comment by 4l3x2k** [comment]
Awesome. Keep on.

**Comment by 4l3x2k** [comment]
Do not forget to test your openwebif video/osd grab!

**Comment by petrkr** [comment]
I do not have sf8008 here. So I can not test it
anyway image is there https://openvision.yacp.net/images/sf8008/

feed I will upload later, but for flash you do not need it

**Comment by IanSav** [comment]
> After last commits made I see that shape rect need the size attribute.
> 
> @IanSav
> Do not forget that the html rendering (map > area > shape="rect") need absolute positions!
> So
> 
> ```
> shape="rect" coords="0,0,10,10"
> ```
> 
> does not say that the rect is 10 in height and width!
> It is more like "span over"!
> 
> EDIT
> "span to" not "span over"

The "pos" attribute is *always* the centre point of the remote control button.  The "pos" attribute is used by the help engine as the centre of the circle drawn over the button by the help engine.  The "radius", "vertices" and "size" attributes are the offsets from the centre "pos" attribute.  That is, "radius" is the radius of a "circle" from the "pos" centre.  The "vertices" are the offset of each point from the centre "pos", elements of the "verticies" list CAN be negative if the vertex is above or to the left of the centre point.  The "size" is the width and height of the rectangle that is centred by "pos".

There has been talk that "size" also become offsets from the centre but this has not yet been confirmed.

All remote control images should be scaled so that the height is always 500 pixels so long as the width is between about 100 to 150 pixels.  If the remote is very wide then the max width should be 150 pixels and the image height set to 500 pixels with the image padded top and bottom to fit the 500 pixel allowance.
.

**Comment by IanSav** [comment]
When you are looking for an image to use as the background for a remote control try to use an image that is as clear as possible and maintains a high contrast so that the features and edges of the buttons can be seen clearly.

**Pull request merged**
