### PR TITLE
[NetworkSetup] Fix ok and save button Actions ...

### PR DESCRIPTION
**Pull request by fairbird**
19:33:05.8394 [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK'.
19:33:05.8401 [ActionMap] Keymap 'OkCancelActions' -> Unknown action 'OK'! (Typo in keymap?)
......................
19:33:27.0854 [InfoBarGenerics] Key: 399 (Make) KeyID='KEY_GREEN'.
19:33:27.0862 [ActionMap] Keymap 'SetupActions' -> Unknown action 'save'! (Typo in keymap?)
19:33:27.0867 [ActionMap] Keymap 'ConfigListActions' -> Unknown action 'save'! (Typo in keymap?)

### CODE REVIEW

**Comment by norhap** [comment]
Thanks @fairbird just a detail, if we no longer take that boolean condition into consideration, you must also remove it from the tuple of the statement. 
def restartLan(self, ret=False):
to
def restartLan(self):

**Comment by fairbird** [comment]
I did not test it yet .. I have add commit depend on some feedback from some friends ...
I need to test it latter ...

**Comment by fairbird** [comment]
@norhap
I have sent to him the correction to test it and he said (The buttons works again) ..
And You need to remove 
> ret=False

from def restartLan ...

But as he said also the feature does not work correctly ... after press green button the new change of mac address does not save it still old mac appear (not as like on ATV image) .. 
Please test it from your side (I don't have device right now)

**Comment by persianpros** [comment]
@fairbird 

Please do not disable "edit" checkbox in your PRs, I can't edit this PR so I can not remove the "ret=False" and you need to do it yourself.

**Pull request closed without merging**
