### PR TITLE
[LocationBox.py] Update embedded screen

### PR DESCRIPTION
**Pull request by IanSav**
Update the embedded screen to use the new resolution based scaling engine.

### CODE REVIEW

**Review by norhap — COMMENTED** [review]
I have not noticed any changes regarding this.
there are still two problems present:

`screen 'LocationBox' rejected as it does not offer all the mandatory widgets 'filetext, quickselect'!`
and...
There is no change, still wrong for xres1920 and  yres1080, the items height are cut in this type of skin ...
for 1280x720 no problems. 

I remind you that I continue with the old 11.1 408 ... so I don't know if this revision is the correct one to revise this commit.

**Comment by IanSav** [comment]
The only change is to rework the embedded screen to use the new scaling engine.

1. Have you updated the skin to account for the new widgets?
2. Please describe any scaling issues you are experiencing.

**Comment by persianpros** [comment]
@IanSav @norhap 

Is this PR ok to merge?

**Comment by IanSav** [comment]
I thought so.

**Pull request merged**
